#!/usr/bin/env sh

CALLING_DIR=$(pwd)

DISTRO_NAME=$(awk -F= '/^NAME/{print $2}' /etc/os-release | tr -d '"')

install_package() {
    local package=$1
    case "$DISTRO_NAME" in
        "Debian GNU/Linux"|"Ubuntu"|"Pop\!_OS")
            echo "Installing package $package..."
            sudo apt-get install -y "$package"
            ;;
        *)
            echo "Package manager not supported"
            return 1
            ;;
    esac
}

echo "Checking dependencies for wayland-config..."

if ! fc-list | grep -iq "Iosevka Term SS09"; then
    name=PkgTTC-SGr-IosevkaTermSS09-29.2.1
    wget -P /tmp/ "https://github.com/be5invis/Iosevka/releases/download/v29.2.1/$name.zip"
    sudo unzip -d "/tmp/$name/" "/tmp/$name.zip"
    sudo mv "/tmp/$name/SGr-IosevkaTermSS09-Regular.ttc" /usr/share/fonts/
    sudo fc-cache -f -v
    sudo rm -rf "/tmp/$name/"
fi

if ! which wl-copy > /dev/null 2>&1; then
    install_package wl-clipboard
fi

if ! which sway > /dev/null 2>&1; then
#
# Here's the begining of what is required to install it manually...
#
# cd /tmp/
# git clone https://github.com/swaywm/sway.git
# LATEST_TAG=$(git tag | grep '^[0-9]*[0-9]\.[0-9][0-9]*\.*[0-9]*$' | sort -V | tail -n 1)
# git checkout "tags/$LATEST_TAG"
#
    install_package sway
fi

if ! which bemenu > /dev/null 2>&1; then
    install_package bemenu
fi

if ! which brightnessctl > /dev/null 2>&1; then
    install_package brightnessctl
fi

if ! which pavucontrol > /dev/null 2>&1; then
    install_package pavucontrol
fi

cd "$CALLING_DIR" || exit 1
