#!/usr/bin/env sh

hydrate_home_with_waylandconfig() {

    wayland_config="$HOME/wayland-config/.config"
    wayland_bin="$HOME/wayland-config/.local/bin"
    home_config="$HOME/.config"
    home_bin="$HOME/.local/bin"

    /bin/mv -v "$HOME/wayland-config/.git" "$HOME/.git-wayland-config"

    /bin/mv -v "$wayland_config/git/exclude-wayland-config" "$home_config/git"

    for dir in shell sway foot Code; do
        rsync -r --remove-source-files "$wayland_config/$dir" "$home_config"
        echo "$home_config/$dir <- $wayland_config/$dir"
    done

    rsync -r --remove-source-files "$wayland_bin/wayland-config" "$home_bin"
    echo "$home_bin/wayland-config <- $wayland_bin/wayland-config"

    /bin/mv -v "$HOME/wayland-config/.xkb" "$HOME"
}

if [ ! -d "$HOME/.git-wayland-config" ]; then

    "$HOME/wayland-config/.config/shell/wayland-config/dependencies"

    hydrate_home_with_waylandconfig
fi
